name: beans_alert
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^7.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.7
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  cloud_firestore:  ^6.0.1
  fluttertoast:  ^8.0.9
  font_awesome_flutter : ^10.3.0
  email_sender: ^2.1.0
  mailer: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/ico/
    - assets/fonts/

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
          weight: 400